training:
  #name: 600kdataset
 # name: 150dataset
  name: week8
  description: Training on frame window dataset clipped all far
  experiment_id: eval
  extra_notes: none
  logs_dir: ../logs/training/eval/
  is_train: true
  device: cuda:0
  batch_size: 32
  num_workers: 16
  test_size: 0.1
  n_epochs: 500
  append_loss_every: 500
  print_every: 500
  validate_every: 16014
  save_every: 16014
  save_every_nepochs: 5
  start_epoch: 0
  start_iteration: 0
  visualize_every: 750
  apply_metrics_every: 16014
  use_scheduler: True
  apply_metrics_batch_count: 5 # number of batches to apply additional metrics on
  load_ckpt: True
  #ckpt_path: logs/fullTrain/fullTrain4Continue/2024_08_08_14_33_28/checkpoints/epoch-latest.ckpt
  #ckpt_path: logs/training/week7/overfit/overfit-10/2024_11_28_03_19_27/checkpoints/epoch-latest.ckpt
  #ckpt_path: ../logs/training/week7/overfit/overfit-10/2024_11_28_03_19_27/checkpoints/epoch-latest.ckpt
  #ckpt_path: ../logs/training/week7/train_full/train_full/2024_11_28_14_40_42/checkpoints/epoch-best.ckpt
  #ckpt_path: ../logs/training/week7/600kdataset/train_full/2024_11_28_21_34_06/checkpoints/epoch-best.ckpt
  #ckpt_path: ../logs/training/week7/150dataset/train_full/2024_11_29_06_50_43/checkpoints/epoch-best.ckpt
  ckpt_path: ../logs/training/week8/20kFarDataset/train_full/2024_12_01_04_12_28/checkpoints/epoch-best.ckpt
  #ckpt_path: "../logs/training/siamese-resnet/visual_samples_100k/2024_11_14_03_02_33/checkpoints/epoch-best.ckpt"
  #ckpt_path: "../logs/training/eval/fc/10k/uniform/2024_11_14_12_40_23/checkpoints/epoch-18.ckpt"
  #ckpt_path: ../logs/training/siamese-lin-bn-conv/uniform_samples_200k/2024_11_14_04_21_24/checkpoints/epoch-best.ckpt
dataset:
  dataset_field: visual_sim_matches
  path: None
  overfit_size: 5
  split: train # train | valid | test
  is_overfit: False

  sim_matches:
    class_filepath: ./datasets/SimMatches.py 
    class: SimMatches
    path: ./raw_dataset/match_pairs/eval/100k/text

  visual_sim_matches:
    class_filepath: ./datasets/VisualSimMatches.py 
    class: VisualSimMatches
    #path: ./raw_dataset/match_pairs/eval/200k/visual
   # path: ./raw_dataset/frame_pairs_full_clipped_150_30
    #path: ./raw_dataset/frame_pairs_full_clipped_150_30_fixed
    path: ./raw_dataset/frame_pairs_far
  


model:
  model_field: siamese
  
  dummy_classifier:
    model_filepath: ./pytorchmodels/DummyClassifier.py
    model_class: DummyClassifier
    lr: 0.01
    losses: acc
    weight_init: None 
    criterion: CE
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1

  siamese:
    model_filepath: ./pytorchmodels/Siamese.py
    model_class: Siamese
    metrics: None
    lr: 1.0e-3
    losses: acc,cont,bce,cosp,cosn
    weight_init: None
    scheduler_step_size: 50
    scheduler_gamma: 0.5
    use_visual: False
    use_combined: True
    use_bb: True
  



