training:
  name: overfit
  description: Debug
  experiment_id: overfit-10
  extra_notes: none
  logs_dir: ../logs/training/week7/
  is_train: true
  device: cuda:0
  batch_size: 32
  num_workers: 16
  test_size: 0.1
  n_epochs: 500
  append_loss_every: 2
  print_every: 2
  validate_every: 5643
  save_every: 100
  save_every_nepochs: 100000000000000000000000000000000
  start_epoch: 0
  start_iteration: 0
  visualize_every: 10
  apply_metrics_every: 2033
  use_scheduler: True
  apply_metrics_batch_count: 5 # number of batches to apply additional metrics on
  load_ckpt: False
  ckpt_path: logs/fullTrain/fullTrain4Continue/2024_08_08_14_33_28/checkpoints/epoch-latest.ckpt

dataset:
  dataset_field: visual_sim_matches
  path: None
  overfit_size: 5
  split: train # train | valid | test
  is_overfit: False

  sim_matches:
    class_filepath: ./datasets/SimMatches.py 
    class: SimMatches
    path: ./raw_dataset/match_pairs/eval/100k/text

  visual_sim_matches:
    class_filepath: ./datasets/VisualSimMatches.py 
    class: VisualSimMatches
    #path: ./raw_dataset/match_pairs/eval/200k/visual
    path: "./raw_dataset/frame_pairs_overfit"
  


model:
  model_field: siamese
  
  dummy_classifier:
    model_filepath: ./pytorchmodels/DummyClassifier.py
    model_class: DummyClassifier
    lr: 0.01
    losses: acc
    weight_init: None 
    criterion: CE
    scheduler_step_size: 75
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1

  siamese:
    model_filepath: ./pytorchmodels/Siamese.py
    model_class: Siamese
    metrics: None
    lr: 1.0e-3
    losses: acc,cont,bce,cosp,cosn
    weight_init: None
    scheduler_step_size: 25
    scheduler_gamma: 0.5
    use_visual: True
    use_combined: True
  



